# Generated by Django 4.2 on 2025-12-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_roles', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id_lectura', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_sensor', models.ForeignKey(db_column='id_sensor', on_delete=django.db.models.deletion.CASCADE, to='api1.sensor')),
            ],
            options={
                'db_table': 'lectura_sensor',
            },
        ),
    ]
